language: node_js

node_js:
  - 6

cache: bundler

branches:
  only:
    - master

env:
  global:
    - DEPLOY_BRANCH=gh-pages
    - BUILD_TARGET=dist

before_script:
  - npm install -g gulp-cli
  - npm install -g mocha
script: npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    branch: master